name: netlify-plugin-contextual-basic-auth
inputs:
  - name: username
    description: Username for http basic auth
    required: true
  - name: password
    description: Password for http basic auth
    required: true
  - name: context
    description: An array of which contexts should have auth [production, deploy-preview, branch-deploy]
    required: true
  - name: branch
    description: Optional branch name to match against
  - name: path
    description: Header path match string for basic auth
    default: /*
  - name: file
    description: path to `_headers` file
    default: 'public/_headers'
