version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    config:
      threshold: 300
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    config:
      threshold: 6
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
  eslint:
    enabled: false
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
        - TODO
        - todo
        - console.log
  nodesecurity:
    enabled: true
  markdownlint:
    enabled: false
  csslint:
    enabled: false
  coffeelint:
    enabled: false
  # SASS Lint requires a .sass-lint.yml file in the repo in order to tweak settings.
  # Without the .sass-lint.yml file it will run with the defaults.
  # Defaults file: https://github.com/sasstools/sass-lint/blob/master/lib/config/sass-lint.yml
  sass-lint:
    enabled: true
exclude_patterns:
  - node_modules/
  - "**/__tests__/"
  - "**/tests/**/*"
  - "package.json"
  - "webpack.config.js"
  - "**.min.*"
