version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
  eslint:
    enabled: false
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
        - TODO
        - todo
        - console.log
  nodesecurity:
    enabled: true
  markdownlint:
    enabled: false
  csslint:
    enabled: false
  coffeelint:
    enabled: false
  # SASS Lint requires a .sass-lint.yml file in the repo in order to tweak settings.
  # Withouth the .sass-lint.yml file it will run with the defaults.
  # Defaults file: https://github.com/sasstools/sass-lint/blob/master/lib/config/sass-lint.yml
  sass-lint:
    enabled: true
  # SCSS Lint requires a .scss-lint.yml file in the repo in order to tweak settings.
  # Withouth the .scss-lint.yml file it will run with the defaults.
  # Defaults file: https://github.com/brigade/scss-lint/blob/master/config/default.yml
  scss-lint:
    enabled: false
exclude_patterns:
  - node_modules/
  - "**/__tests__/"
  - "**/tests/**/*"
  - "package.json"
  - "webpack.config.js"
  - "**.min.*"
