# BUILD Settings:
# ##############################################################################
[build]
  publish = "public"
  functions = "lambda"

[dev]
  publish = "public"
  port = 64946
  autolaunch = true

# HEADERS - BASIC AUTH
# ##############################################################################
[[headers]]
  for = "/*"
  [headers.values]
    Basic-Auth = "adapt:letmein2020"
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "form-action https:"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    Feature-Policy = "vibrate 'none'; geolocation 'none'; midi 'none'; notifications 'none'; push 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none'; fullscreen 'none'"

# PLUGIN A11Y
# https://github.com/netlify-labs/netlify-plugin-a11y#readme
# ##############################################################################
# [[plugins]]
  # package = "netlify-plugin-a11y"

  # all inputs are optional, we just show you the defaults below
  # [plugins.inputs]

  # required config
  # checkPaths = ['/'] # you can give an array of directories or paths to html files, that you want to run a11y checks on

  ## optional config
  # ignoreDirectories = ['/editor']  # explicitly ignore these directories
  # resultMode = "warn" # is "error" by default

# PLUGIN GATSBY CACHE
# https://github.com/jlengstorf/netlify-plugin-gatsby-cache#readme
# ##############################################################################
[[plugins]]
  package = "netlify-plugin-gatsby-cache"

# PLUGIN LIGHTHOUSE
# https://github.com/netlify-labs/netlify-plugin-lighthouse#readme
# ##############################################################################
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, fails build when a category is below a threshold
  # [plugins.inputs.thresholds]
  #   performance = 0.9
  #   accessibility = 0.9
  #   best-practices = 0.9
  #   seo = 0.9
  #   pwa = 0.9

# REDIRECTS
# ###############################################################################

# API redirect for lambda functions.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/lambda/:splat"
  status = 200

# [[redirects]]
#   from = "/test"
#   to = "/stories/a-win-win-solution/"
#   status = 301
