# BUILD Settings:
# ##############################################################################
[build]
  publish = "public"
  functions = "lambda"

[dev]
  publish = "public"
  port = 64946
  autolaunch = true

# HEADERS - BASIC AUTH
# ##############################################################################
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "form-action https:"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    Permissions-Policy = "vibrate=(), geolocation=(), midi=(), notifications=(), push=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), speaker=()"
    Authorization = "Basic YWRhcHQ6bGV0bWVpbjIwMjE="
# SUBMIT SITEMAP PLUGIN
# https://www.npmjs.com/package/netlify-plugin-submit-sitemap
# ###############################################################################
# [[plugins]]
# package = "netlify-plugin-submit-sitemap"
#   [plugins.inputs]
#     # Path to the sitemap URL (optional, default = /sitemap.xml)
#     sitemapPath = "/sitemap/sitemap-index.xml"
# REDIRECTS are located in static/_redirects
# ###############################################################################
