# BUILD Settings:
# ##############################################################################
[build]
  publish = "public"
  functions = "lambda"

[dev]
  publish = "public"
  port = 64946
  autolaunch = true

# HEADERS - BASIC AUTH
# ##############################################################################
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "form-action https:"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    Permissions-Policy = "vibrate=(), geolocation=(), midi=(), notifications=(), push=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), speaker=()"
    X-Frame-Options = "DENY"
[[context.dev.headers]]
  for = "/*"
  [context.dev.headers.values]
    Basic-Auth = "adapt:letmein2021"
[[headers]]
  for = "/editor"
  [headers.values]
    X-Frame-Options = "ALLOWALL"

# PLUGINS
# ##############################################################################

# Fetch vault plugin needs to come before any of the contextual environment
# variable plugins so they can act on the new vars.
[[plugins]]
  package = "/plugins/netlify-plugin-vault-variables"
  [plugins.inputs]
    endpoint = 'https://vault.stanford.edu'
    # Order doesn't matter here as these will be fetch asyncronously. Try not to have dupes.
    secrets = ['secret/data/projects/adapt/giving']
    # Set which environment variables to use for the approle login
    secretId = 'VAULT_SECRET_ID'
    roleId = 'VAULT_ROLE_ID'

[[plugins]]
  package = 'netlify-plugin-contextual-env'
  [plugins.inputs]
    mode = 'prefix'

[[plugins]]
  package = "@netlify/plugin-gatsby"

# CONTEXTUAL PLUGINS
# ##############################################################################
# Production context:
# All deploys from the main repository branch
# will inherit these settings.
[context.main]
  # Deploys from main branch run this plugin in the build.
  # Plugins context requires double brackets.
  [[context.main.plugins]]
    package = "netlify-plugin-submit-sitemap"
    [context.main.plugins.inputs]
      # Path to the sitemap URL (optional, default = /sitemap.xml)
      sitemapPath = "/sitemap/sitemap-index.xml"

# REDIRECTS are located in static/_redirects
# ###############################################################################
