name: Lint
on:
  push:
  # pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set the correct Node version using nvm
        shell: bash -l {0}
        run: nvm install
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run tsc
